#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

subcommand="$1"
shift

function add-numbers(){
  no_nums="$(pbpaste)"
  with_nums="$(echo "$no_nums" | ts-node "$SCRIPT_DIR/add-numbers-to-first-elem-in-line.ts")"
  diff -u <(echo "$no_nums") <(echo "$with_nums") | diffr | less -R
  ask "Copy the version with nums to the clipboard?" && echo "$with_nums" | pbcopy
}

function build-view(){
  ts-node "$SCRIPT_DIR/build-view.ts"
}

case $subcommand in
  [aA][nN]|add-numbers) 
    add-numbers
    ;;
  [bB][vV]|build-view)
    build-view
    ;;
  *)
    echo "Usage: ob2util <subcommand>"
    echo "Subcommands:"
    echo "  an|add-numbers"
    ;;
esac

